version: "2"
virtualmachines:
  - name: workstation
    image: ubuntu2204
    machine_type: n1-standard-4
    allow_external_ingress:
      - hostname: workstation
        port: 9000
        protocol: https
containers: []
